### ISSUE TITLE
Committed NuGet package does not match

### ISSUE THREAD

**Issue by jho1965us** [appccelerate/bootstrapper#1]
I am new to versioning handling in NuGet packages but it seems to me that bootstrapper depends on old versions of some appccelerate packages that is no longer available
If I use precompiled NuGet pakages I get a run time version error
If I try build from source I have to go modify version numbers in *.cproj and packages.config to match what is actualy available through NuGet

**Comment by ursenzler** [comment]
That is because Nuget per default takes the lowest possible version of a dependency.
Can you try to update all Appccelerate packages after you installed the bootstrapper package?

I have to link the correct version. Thanks for reporting.

**Comment by jho1965us** [comment]
when you say:
Can you try to update all Appccelerate packages after you installed the bootstrapper package?
do you refer to changes like those in: 36c4bf95eac7e88dad12804a039108b2db8a4220?
(at the moment this is the only changes in fork jho1965us/bootstrapper, I did those changes by editing the files in a text editor is there supposed to be an easier way?)

**Comment by ursenzler** [comment]
I'm a bit confused.

Do you want to use the Bootstrapper package in one of your projects, or do you want to modify the Bootstrapper source code?

In the first case, make sure that Appccelerate.Fundamentals is updated to the latest version from nuget.org.
In the second case, it shouldn't matter because you rebuild the bootstrapper code against whatever version Fundamentals has on your machine.

**Comment by jho1965us** [comment]
I use Bootstrapper in my own project. First I tried to use the package on NuGet but Visual Studio keept giving errror messages, this is a couple of week agos  I don't remember the exact messages, but it looked as if Bootstrapper needed another version of Fundamentals (or maybe it was some other Appccelerate packages) than the ones available through NuGet 

Then I tried to build from source and I run in to similar problem but by changing the various versions of referenced Appccelerate packages to those available through NuGet I was able to build.
I currently use the Bootstapper build that way in my project.

I currently have no plan to do other changes to Bootstrapper.

**Comment by ursenzler** [comment]
Okay, I understand now.

The problem is that I had forgotten to set the exact version of the Appccelerate.Fundamentals package that the Bootstrapper packages references. This version is specified inside the Bootstrapper package.
Nuget allows to use ranges.

The default behavior of nuget is that it downloads to Fundamentals package with the lowest allowed version - the wring version - thus leading to a build warning that you use a different version of Fundamentals than the one Bootstrapper was built against.
A quick fix is, to manually update the Fundamentals package (e.g. in the manage nuget package references dialog) to the latest version.
Then everything should be fine again.

The reason I did not already change the version of the reference is that I have to do this for every package. And the next version of nuget probably changes its default behavior.
But I should take the effort, it is just too confusing.

Thanks for the feedback
Urs
